name: Build PT Ruleset

on:
  workflow_dispatch:
  push:
    paths:
      - 'rule/category-pt.list'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Workspace
        run: |
          mkdir -p build

      - name: Convert List Format
        run: |
          sed 's/^+\.//g;s/^/DOMAIN-SUFFIX,/' \
          rule/category-pt.list \
          > build/category-pt.txt

      - name: Download Mihomo
        run: |
          wget -q \
          https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64-compatible.gz \
          -O mihomo.gz

          gunzip mihomo.gz
          mv mihomo mihomo-bin

          chmod +x mihomo-bin

      - name: Build MRS
        run: |
          ./mihomo-bin convert-ruleset domain text \
          build/category-pt.txt \
          rule/category-pt.mrs

      - name: Commit MRS
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add rule/category-pt.mrs

          git diff --cached --quiet || \
          git commit -m "Update category-pt.mrs"

          git push

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            rule/category-pt.mrs
